theme: jekyll-theme-minimal
title: <br> <span style="color:grey"> 25<sup>th</sup> and 26<sup>th</sup> of November <br> Sorbonne Cluster for Artificial Intelligence (SCAI) </span>
description: ''
github:
  is_user_page: false
  is_project_page: false
logo: /docs/assets/logo_neurips_in_paris_NEW.svg
